### ISSUE TITLE
请问这个如何使用

### ISSUE THREAD

**Issue by WeiCY** [AYJk/AYTikTokPod#10]
您好，第一次接触逆向。请问您这个工程是如何使用的？看issues里面有cocoapods？能详细说一下嘛

**Comment by MurphLu** [comment]
1. 安装MonkeyDev 并创建MonkeyDev 工程 https://github.com/AloneMonkey/MonkeyDev/wiki
2.工程目录下新建Podfile，引入AYTikTokPod库
3.下载Tiktok.ipa，并拖入工程相应目录
4.运行
