### ISSUE TITLE
谢谢作者的思路

### ISSUE THREAD

**Issue by xiaobovlog** [AYJk/AYTikTokPod#11]
前几天我再mac上使用了一下，没有成功。
今天我用Fiddler代理写了一个教程，安卓、iOS通用的。是改请求数据实现的，分享一下
https://www.cnblogs.com/storyline/articles/10255132.html

**Comment by xiaobovlog** [comment]
已经成功装上作者给的版本了，太赞了。pod install 之后，关闭整个项目，通过DouYin.xcworkspace这个打开项目就可以了

**Comment by jackylee1** [comment]
你好，请问你的podfile是怎样的
