### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by Nododo** [AYJk/AYTikTokPod#12]
你好，请问怎么判断出 AWESettingItemModel 属性 cellTappedBlock 里的参数是void 而switchChangedBlock 则没有做出判断？

**Comment by AYJk** [comment]
具体你可以参考下 [http://bbs.iosre.com/t/block/6779](http://bbs.iosre.com/t/block/6779)
`switchChangedBlock`是这个Model的属性，Hook里面没用到，我只是拷贝出来了而已。所以就用id了。
