### ISSUE TITLE
Failed to write file "default.profraw": Operation not permitted

### ISSUE THREAD

**Issue by cashleeboy** [AYJk/AYTikTokPod#13]
AwemeI18n[6532:2761379] [ApplicationLifecycle] Windows were created before application initialzation completed. This may result in incorrect visual appearance.
LLVM Profile Error: Failed to write file "default.profraw": Operation not permitted

**Comment by AYJk** [comment]
反调试问题。
[https://github.com/AloneMonkey/MonkeyDev/issues/68](https://github.com/AloneMonkey/MonkeyDev/issues/68)
