### ISSUE TITLE
编译出现错误`linker command failed with exit code 1`

### ISSUE THREAD

**Issue by raighnew** [AYJk/AYTikTokPod#14]
/clang:-1: linker command failed with exit code 1 (use -v to see invocation)

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/6561527/52339137-3d3d8f80-2a47-11e9-99d9-f7f4157c52d2.png">

**Comment by AYJk** [comment]
用Xcode

**Comment by raighnew** [comment]
噗，就是用Xcode啊

PengFei Huang <notifications@github.com>于2019年2月11日 周一10:04写道：

**Comment by AYJk** [comment]
为何你的Xcode这么高级。。。
给的错误信息太少了，单单一个`linker command failed with exit code 1`
我没法帮你定位问题

**Comment by raighnew** [comment]
![image](https://user-images.githubusercontent.com/6561527/52543744-e937ff80-2de6-11e9-94b8-87bf5fcde806.png)

**Comment by raighnew** [comment]
建好项目后，把ipa拉进目录，建好podfile。install一下，在Xcode里编译就出现了错误

**Comment by AYJk** [comment]
检查下`AYTikTokPod`有没有Pod好吧，报错原因是找不到`AYTikTokPod`，检查下Search Framework Path。这个只能自己去处理了，可能原因有很多。

**Comment by Devil-Cong** [comment]
我也遇到相同的问题，Podfile 文件如下：
```
source 'https://github.com/AloneMonkey/MonkeyDevSpecs.git'

use_frameworks!	

target 'TestDylib' do
     pod 'AYTikTokPod'
end
```
`pod install` 也提示成功了

![image](https://user-images.githubusercontent.com/13516290/52544045-2b624080-2de9-11e9-9676-d5a025f377e9.png)

`.ipa` 拖到 `TargetApp` 了，不过貌似实际 `.ipa` 文件的实际路径并不在 `TargetApp` 文件夹里面，而是在上一层

![image](https://user-images.githubusercontent.com/13516290/52544394-ab89a580-2deb-11e9-995e-6867b9d0cc40.png)


然后运行之后，遇到了相同的报错

![image](https://user-images.githubusercontent.com/13516290/52544218-5731f600-2dea-11e9-9e1d-1c0e3d52aa78.png)

麻烦大神帮忙看下，谢谢！

**Comment by Devil-Cong** [comment]
+1 
遇到相同的问题

**Comment by AYJk** [comment]
@raighneweng @Devil-Cong 请确保`pod install`之后，是通过`****.xcworkspace`打开工程的，而不是`****.xcodeproj`

**Comment by Devil-Cong** [comment]
@AYJk 可以了，成功安装跑起来了，谢谢~

**Comment by Devil-Cong** [comment]
再多问一句，多地区切换是指用不同区的 `TikTok.ipa` 重新 `build` 一次，还是说在任意 `build` 好的 App 里面切换就可以了？

**Comment by AYJk** [comment]
登录之后，在`设定`中进行切换`TikTok小插件`。登录自备梯子。

**Comment by Devil-Cong** [comment]
get it. 多谢~
