### ISSUE TITLE
我的姿势错了吗?

### ISSUE THREAD

**Issue by swiftxy** [AYJk/AYTikTokPod#3]
```
2018-12-25 17:26:37.380884+0800 AwemeI18n[3811:1248803] [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x280642c80, domain=1, instance=1>
2018-12-25 17:26:37.395161+0800 AwemeI18n[3811:1248803] [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x2806432e0, domain=1, instance=1>
2018-12-25 17:26:37.459599+0800 AwemeI18n[3811:1248803] mobilecv2: 1.0.3.1030
```

**Comment by AYJk** [comment]
貌似是因为iOS12.1的问题？不确定，手头没有iOS12.1的机器，等下借个手机测试下看看。
看看这个的回答。
[how-to-troubleshoot-resolve-signal-strength-query-returned-error-logs-that-are](https://stackoverflow.com/questions/53526194/how-to-troubleshoot-resolve-signal-strength-query-returned-error-logs-that-are)

**Comment by swiftxy** [comment]
iOS版本 12.1.2  7P, 进去都是黑的, 没有什么内容. 😢

**Comment by AYJk** [comment]
@JiaLiangoooo 测试没问题，请注意CocoaPods的`Target`不要搞错了。是`ProjectNameDylib`，而不是`ProjectName`。

**Comment by swiftxy** [comment]
我犯了一个致命的错误.

**Comment by QA411** [comment]
如何解决的？我也遇到了 Signal strength query returned error

**Comment by jezzhu** [comment]
> ```
> 2018-12-25 17:26:37.380884+0800 AwemeI18n[3811:1248803] [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x280642c80, domain=1, instance=1>
> 2018-12-25 17:26:37.395161+0800 AwemeI18n[3811:1248803] [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x2806432e0, domain=1, instance=1>
> 2018-12-25 17:26:37.459599+0800 AwemeI18n[3811:1248803] mobilecv2: 1.0.3.1030
> ```



你好， 我遇到跟你一样的问题，请问你是如何解决的？

**Comment by AYJk** [comment]
@hijackwust 这个不是问题原因，注意CocoaPods的Target不要搞错了。是ProjectNameDylib，而不是ProjectName。看看这里有没有问题

**Comment by IOS6** [comment]
在 edit scheme -> Run -> Environment Variables 添加 OS_ACTIVITY_MODE disable，如下图。是xcode的问题
![image](https://user-images.githubusercontent.com/15925100/54263806-abc4be80-45ac-11e9-8853-892cb0be8a54.png)
