### ISSUE TITLE
再冒昧问下大佬

### ISSUE THREAD

**Issue by chuanzhang2018** [AYJk/AYTikTokPod#5]
是否是直接新建一个MonkeyDev的项目 然后拖入ipa 然后直接编译就可以了  还有其他操作步骤吗

**Comment by AYJk** [comment]
看Monkey的Wiki，用cocoapods 集成`AYTikTokPod`，注意Tartget不要弄错。拖入ipa，编译运行。

**Comment by chuanzhang2018** [comment]
大佬 jokunTiktok pod install AYTikTokPod
[!] Unknown command: `AYTikTokPod`

Usage:

    $ pod install

      Downloads all dependencies defined in
      `Podfile` and creates an Xcode Pods
      library project in `./Pods`.

**Comment by AYJk** [comment]
@chuanzhang2018   `pod repo update`
