### ISSUE TITLE
IPA包是不是有问题，我下载下来直接放到MONKEY里面RUN都是无任何视频，包括搭了梯子

### ISSUE THREAD

**Issue by Chris958** [AYJk/AYTikTokPod#6]

**Comment by AYJk** [comment]
注意几点：

1. MonkeyDev并集成AYTikTokPod
2. CocoaPods的Target是对应的Dylib

**Comment by Chris958** [comment]
我确定自己的操作没有问题，集成打包后依旧是无视频状态，无法登陆状态，Xcode9.3  iOS11.4

**Comment by AYJk** [comment]
我测试过是没问题。无视频无法登陆说明还是集成有问题。
发一下你的Podfile

**Comment by Chris958** [comment]
我找到问题了，多谢解答

**Comment by QA411** [comment]
hi 我也遇到相同问题，如何解决？

**Comment by QA411** [comment]
hi 我也遇到相同问题，如何解决？
