### ISSUE TITLE
hi 我也遇到相同问题，如何解决？

### ISSUE THREAD

**Issue by QA411** [AYJk/AYTikTokPod#7]
hi 我也遇到相同问题，如何解决？

**Comment by AYJk** [comment]
#8

**Comment by QA411** [comment]
小老板，我的pod都正常。就是run以后  抖音还是无数据，被屏蔽了。AYTikTokPod pod进入工程后不需要做其他的了嘛？

**Comment by AYJk** [comment]
把你的Podfile文件发上来

**Comment by QA411** [comment]
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/AloneMonkey/MonkeyDevSpecs.git'

# platform :ios, '9.0'

target 'fangxian' do


end

target 'fangxianDylib' do
 

pod 'FLEX'
#pod 'MonkeyDevPod', '2.0.0'
pod 'AYTikTokPod'

end

**Comment by QA411** [comment]
加上use_frameworks! 就好了 可以了
