### ISSUE TITLE
pod不成功

### ISSUE THREAD

**Issue by gu2890961** [AYJk/AYTikTokPod#8]
你好，能不能提供下Podfile，我一直install失败，说什么没有指定版本号，下面是我的
source 'https://github.com/AYJk/AYTikTokPod' #不可少
use_frameworks!

target 'MonkeyPodDylib' do
pod 'AYTikTokPod'
end
错误信息：
Analyzing dependencies
[!] An unexpected version directory `Resources` was encountered for the `/Users/gupeng/.cocoapods/repos/ayjk/AYTikTokPod` Pod in the `AYTikTokPod` repository.

[!] Automatically assigning platform `ios` with version `8.0` on target `MonkeyPodDylib` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by AYJk** [comment]
```
source 'https://github.com/AloneMonkey/MonkeyDevSpecs.git'

use_frameworks!	

target 'TestTikTokDylib' do
     pod 'AYTikTokPod'
end
```
